import type { Node } from "@xyflow/react"
import { Bell, CircleDot, Clock, Droplets, Lightbulb, Power, Radio, Thermometer, Zap } from "lucide-react"
import type { ComponentItem } from "./types"

export const hardwareComponents: ComponentItem[] = [
  {
    id: "button",
    type: "button",
    label: "Button",
    icon: CircleDot,
    color: "text-blue-400",
    bgColor: "bg-blue-500/20",
    category: "Input",
    data: { label: "Button", pin: "GPIO4" },
  },
  {
    id: "motion",
    type: "button",
    label: "Motion Sensor",
    icon: Radio,
    color: "text-purple-400",
    bgColor: "bg-purple-500/20",
    category: "Input",
    data: { label: "Motion", pin: "GPIO14" },
  },
  {
    id: "temp",
    type: "button",
    label: "Temp Sensor",
    icon: Thermometer,
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/20",
    category: "Input",
    data: { label: "Temperature", pin: "GPIO27" },
  },
  {
    id: "aht20",
    type: "button",
    label: "AHT20 Sensor",
    icon: Droplets,
    color: "text-teal-400",
    bgColor: "bg-teal-500/20",
    category: "Input",
    data: { label: "AHT20 Temp/Humidity", pin: "GPIO6" },
  },
  {
    id: "light",
    type: "light",
    label: "Light",
    icon: Lightbulb,
    color: "text-amber-400",
    bgColor: "bg-amber-500/20",
    category: "Output",
    data: { label: "Light", pin: "GPIO5", isOn: false },
  },
  {
    id: "led",
    type: "light",
    label: "Status LED",
    icon: Lightbulb,
    color: "text-green-400",
    bgColor: "bg-green-500/20",
    category: "Output",
    data: { label: "Status LED", pin: "GPIO2", isOn: false },
  },
  {
    id: "rgb_led",
    type: "light",
    label: "RGB LED Array",
    icon: Lightbulb,
    color: "text-violet-400",
    bgColor: "bg-violet-500/20",
    category: "Output",
    data: { label: "RGB LED Array", pin: "GPIO8", isOn: false },
  },
  {
    id: "buzzer",
    type: "light",
    label: "Buzzer",
    icon: Bell,
    color: "text-rose-400",
    bgColor: "bg-rose-500/20",
    category: "Output",
    data: { label: "Buzzer", pin: "GPIO5", isOn: false },
  },
]

export const ALL_LOGIC_NODES: ComponentItem[] = [
  {
    id: "when_pressed",
    type: "trigger",
    label: "When Pressed",
    icon: Zap,
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/20",
    category: "Trigger",
    data: { label: "When Pressed", triggerType: "on_press" },
  },
  {
    id: "when_released",
    type: "trigger",
    label: "When Released",
    icon: Zap,
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/20",
    category: "Trigger",
    data: { label: "When Released", triggerType: "on_release" },
  },
  {
    id: "when_on",
    type: "trigger",
    label: "When On",
    icon: Zap,
    color: "text-green-400",
    bgColor: "bg-green-500/20",
    category: "Trigger",
    data: { label: "When On", triggerType: "on_turn_on" },
  },
  {
    id: "when_off",
    type: "trigger",
    label: "When Off",
    icon: Zap,
    color: "text-red-400",
    bgColor: "bg-red-500/20",
    category: "Trigger",
    data: { label: "When Off", triggerType: "on_turn_off" },
  },
  {
    id: "turn_on",
    type: "action",
    label: "Turn On",
    icon: Power,
    color: "text-green-400",
    bgColor: "bg-green-500/20",
    category: "Action",
    data: { label: "Turn On", actionType: "turn_on" },
  },
  {
    id: "turn_off",
    type: "action",
    label: "Turn Off",
    icon: Power,
    color: "text-red-400",
    bgColor: "bg-red-500/20",
    category: "Action",
    data: { label: "Turn Off", actionType: "turn_off" },
  },
  {
    id: "toggle",
    type: "action",
    label: "Toggle",
    icon: Power,
    color: "text-amber-400",
    bgColor: "bg-amber-500/20",
    category: "Action",
    data: { label: "Toggle", actionType: "toggle" },
  },
  {
    id: "delay_500ms",
    type: "delay",
    label: "Wait 500ms",
    icon: Clock,
    color: "text-orange-400",
    bgColor: "bg-orange-500/20",
    category: "Timing",
    data: { label: "Wait", duration: "500ms" },
  },
  {
    id: "delay_1s",
    type: "delay",
    label: "Wait 1s",
    icon: Clock,
    color: "text-orange-400",
    bgColor: "bg-orange-500/20",
    category: "Timing",
    data: { label: "Wait", duration: "1s" },
  },
  {
    id: "delay_5s",
    type: "delay",
    label: "Wait 5s",
    icon: Clock,
    color: "text-orange-400",
    bgColor: "bg-orange-500/20",
    category: "Timing",
    data: { label: "Wait", duration: "5s" },
  },
  {
    id: "delay_10s",
    type: "delay",
    label: "Wait 10s",
    icon: Clock,
    color: "text-orange-400",
    bgColor: "bg-orange-500/20",
    category: "Timing",
    data: { label: "Wait", duration: "10s" },
  },
  {
    id: "delay_30s",
    type: "delay",
    label: "Wait 30s",
    icon: Clock,
    color: "text-orange-400",
    bgColor: "bg-orange-500/20",
    category: "Timing",
    data: { label: "Wait", duration: "30s" },
  },
  {
    id: "delay_1min",
    type: "delay",
    label: "Wait 1 min",
    icon: Clock,
    color: "text-orange-400",
    bgColor: "bg-orange-500/20",
    category: "Timing",
    data: { label: "Wait", duration: "60s" },
  },
  {
    id: "light_node",
    type: "light",
    label: "Light",
    icon: Lightbulb,
    color: "text-amber-400",
    bgColor: "bg-amber-500/20",
    category: "Output",
    data: { label: "Light", pin: "GPIO5", isOn: false },
  },
  {
    id: "led_node",
    type: "light",
    label: "Status LED",
    icon: Lightbulb,
    color: "text-green-400",
    bgColor: "bg-green-500/20",
    category: "Output",
    data: { label: "Status LED", pin: "GPIO2", isOn: false },
  },
]

export const LOGIC_CATEGORIES = ["Trigger", "Action", "Timing", "Output"] as const
export const CANVAS_CATEGORIES = ["Input", "Trigger", "Action", "Timing", "Output"] as const
export const ALL_COMPONENTS: ComponentItem[] = [...hardwareComponents, ...ALL_LOGIC_NODES]

export const TRIGGER_OPTIONS = [
  { value: "on_press", label: "When Pressed" },
  { value: "on_release", label: "When Released" },
  { value: "on_turn_on", label: "When On" },
  { value: "on_turn_off", label: "When Off" },
]

export const ACTION_OPTIONS = [
  { value: "turn_on", label: "Turn On" },
  { value: "turn_off", label: "Turn Off" },
  { value: "toggle", label: "Toggle" },
]

export const BOARD_OPTIONS = [
  { value: "esp32-c6-devkitc-1", label: "ESP32-C6 DevKit", framework: "esp-idf" },
  { value: "esp32dev", label: "ESP32 Dev Module", framework: "arduino" },
  { value: "esp32-s3-devkitc-1", label: "ESP32-S3 DevKit", framework: "esp-idf" },
  { value: "esp32-s2-saola-1", label: "ESP32-S2 Saola", framework: "esp-idf" },
  { value: "nodemcu-32s", label: "NodeMCU-32S", framework: "arduino" },
]

export const STARTER_KIT_BOARD = "esp32-c6-devkitc-1"

export const STARTER_KIT_NODES: Node[] = [
  {
    id: "sk-button-1",
    type: "button",
    position: { x: 80, y: 60 },
    data: { label: "Button", pin: "GPIO9" },
  },
  {
    id: "sk-aht20-1",
    type: "button",
    position: { x: 80, y: 200 },
    data: { label: "AHT20 Temp/Humidity", pin: "GPIO6" },
  },
  {
    id: "sk-pir-1",
    type: "button",
    position: { x: 80, y: 340 },
    data: { label: "PIR Motion", pin: "GPIO2" },
  },
  {
    id: "sk-rgb-1",
    type: "light",
    position: { x: 420, y: 130 },
    data: { label: "RGB LED Array", pin: "GPIO8", isOn: false },
  },
  {
    id: "sk-buzzer-1",
    type: "light",
    position: { x: 420, y: 280 },
    data: { label: "Buzzer", pin: "GPIO5", isOn: false },
  },
]
